fail_fast: false
exclude: ^.*\b(migrations)\b.*$
repos:

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]

-   repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
    -   id: autoflake
        args: [
            --in-place,
            --remove-all-unused-imports,
            --ignore-init-module-imports,
            --remove-unused-variables,
        ]


# -   repo: https://github.com/pycqa/isort
#     rev: 6.1.0
#     hooks:
#     -   id: isort

-  repo: https://github.com/PyCQA/docformatter
   rev: v1.7.7
   hooks:
     - id: docformatter
       args: [
           --in-place,
           --blank,
       ]

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [
          --config=pyproject.toml,
          --line-length=120,
          --fix,
        ]
        exclude: .git|__pycache__
      - id: ruff-format
        args: [
          --config=pyproject.toml,
        ]
        exclude: .git|__pycache__